cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    juanzan:
      email: juanzanguitu@gmail.com
      failed_login_attempts: 0
      first_name: Juan
      last_name: Zanguitu
      logged_in: false
      password: $2b$12$Rw5IGpN6QHo8/bbvkfVZB.R/rOOPlFnxHEfKh3UupsfccIwRXnbOi
      password_hint: 123456!asdA
      roles: null
    nlawrence1:
      email: nlawrence1@hawk.iit.edu
      failed_login_attempts: 0
      first_name: Nolan
      last_name: Lawrence
      logged_in: false
      password: $2b$12$2JAyRB17YXf5FCgccJdVzeuu0h6i94BYqXheLZ9iNFy40PTwPS7Vy
oauth2:
  google:
    client_id: null
    client_secret: null
    redirect_uri: null
  microsoft:
    client_id: null
    client_secret: null
    redirect_uri: null
    tenant_id: null
pre-authorized:
  emails: null
